kind: Secret
apiVersion: v1
metadata:
  name: app-con-volumen-generic-webhook-secret
  namespace: samplexecuan
  labels:
    app: app-con-volumen
    app.kubernetes.io/component: app-con-volumen
    app.kubernetes.io/instance: app-con-volumen
    app.kubernetes.io/name: app-con-volumen
    app.kubernetes.io/part-of: app-con-volumen
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-ubi8
data:
  WebHookSecretKey: ODY5ZDMyOTdlMjQwYjcxZg==
type: Opaque
