kind: Secret
apiVersion: v1
metadata:
  name: adelanto-salarial-dev-generic-webhook-secret
  namespace: adelanto-de-salario-dev
  uid: f3e2489c-5aca-4058-91d8-55436bd421d0
  resourceVersion: '365544307'
  creationTimestamp: '2023-03-31T22:27:26Z'
  labels:
    app: adelanto-salarial-dev
    app.kubernetes.io/component: adelanto-salarial-dev
    app.kubernetes.io/instance: adelanto-salarial-dev
    app.kubernetes.io/name: adelanto-salarial-dev
    app.kubernetes.io/part-of: adelanto-salarial-dev
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-11-ubi8
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2023-03-31T22:27:26Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:WebHookSecretKey': {}
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:type': {}
data:
  WebHookSecretKey: ODY5ZDMyOTdlMjQwYjcxZg==
type: Opaque
